name: Create Submission Report Via GitHub Action

on:
    workflow_dispatch:
permissions:
  contents: write

jobs:

  report:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
    - name: Install gcovr from pip
      run: pip install gcovr
    - uses: actions/checkout@v4
    - name: Build Project
      run: make all
    - name: Create Submission Report
      run: ./.github/workflows/create-report.sh
    - uses: docker://pandoc/core:3.5
      with:
        args: -s -o submission-report.docx submission-report.md

    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: "Submission report created via GitHub Action"
